package com.alameer.station.shifts;

import android.app.*;import android.os.*;import android.database.Cursor;import android.graphics.Color;import android.text.InputType;import android.view.*;import android.widget.*;import java.util.*;

public class AdminActivity extends Activity {
    Db db;LinearLayout content;
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new Db(this);home();}
    private void shell(String title){ScrollView scroll=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(18,24,18,50);content.setBackgroundColor(Color.rgb(247,250,252));content.addView(Util.title(this,title));scroll.addView(content);setContentView(scroll);}
    private void home(){shell("إدارة محطة الأمير");Button workers=Util.button(this,"العمال ورموز الدخول");workers.setOnClickListener(v->workers());content.addView(workers);Button pumps=Util.button(this,"الطرمبات والأسعار والقراءات");pumps.setOnClickListener(v->pumps());content.addView(pumps);Button approvals=Util.button(this,"الورديات بانتظار الاعتماد");approvals.setOnClickListener(v->approvals());content.addView(approvals);int pending=db.pendingSyncCount();Button sync=Util.button(this,"مزامنة Google Sheets الآن"+(pending>0?" ("+pending+")":""));sync.setOnClickListener(v->new Sync(this).run(true));content.addView(sync);content.addView(Util.label(this,"تنبيه: أدخل الأسعار والقراءات الافتتاحية قبل بدء أول وردية حقيقية."));}
    private void back(){Button b=Util.button(this,"رجوع");b.setOnClickListener(v->home());content.addView(b);}
    private void workers(){shell("إعداد العمال");try(Cursor c=db.workers()){while(c.moveToNext()){long id=c.getLong(0);String name=c.getString(1),pin=c.getString(2),role=c.getString(3),kind=c.getString(4);Button b=Util.button(this,name+" — "+("NIGHT".equals(kind)?"ليل":"نهار")+("ADMIN".equals(role)?" — مدير":""));b.setOnClickListener(v->workerDialog(id,name,pin,kind,"ADMIN".equals(role)));content.addView(b);}}back();}
    private void workerDialog(long id,String oldName,String oldPin,String oldKind,boolean admin){LinearLayout box=form();EditText name=input("اسم العامل",oldName,false),pin=input("رمز PIN",oldPin,true);Spinner kind=new Spinner(this);kind.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"نهار","ليل"}));kind.setSelection("NIGHT".equals(oldKind)?1:0);box.addView(name);box.addView(pin);if(!admin)box.addView(kind);new AlertDialog.Builder(this).setTitle("تعديل الحساب").setView(box).setPositiveButton("حفظ",(d,w)->{if(name.getText().toString().trim().isEmpty()||pin.getText().toString().trim().length()<4){Toast.makeText(this,"الاسم مطلوب والرمز 4 أرقام على الأقل",Toast.LENGTH_LONG).show();return;}try{db.updateWorker(id,name.getText().toString(),pin.getText().toString(),admin?"DAY":(kind.getSelectedItemPosition()==1?"NIGHT":"DAY"));workers();}catch(Exception e){Toast.makeText(this,"رمز PIN مستخدم لحساب آخر",Toast.LENGTH_LONG).show();}}).setNegativeButton("إلغاء",null).show();}
    private void pumps(){shell("الطرمبات والأسعار");try(Cursor c=db.pumps()){while(c.moveToNext()){long id=c.getLong(0);String name=c.getString(1),fuel=c.getString(2),worker=c.getString(6);double price=c.getDouble(3),reading=c.getDouble(4);long workerId=c.getLong(5);Button b=Util.button(this,name+" — "+fuel+"\nالسعر: "+fmt(price)+" | القراءة: "+fmt(reading)+" | "+worker);b.setOnClickListener(v->pumpDialog(id,name,fuel,price,reading,workerId));content.addView(b);}}back();}
    private void pumpDialog(long id,String oldName,String oldFuel,double oldPrice,double oldReading,long oldWorkerId){LinearLayout box=form();EditText name=input("اسم الطرمبة",oldName,false),fuel=input("نوع الوقود",oldFuel,false),price=input("سعر اللتر",fmt(oldPrice),true),reading=input("القراءة الافتتاحية / الحالية",fmt(oldReading),true);ArrayList<String> names=new ArrayList<>();ArrayList<Integer> ids=db.workerIds();try(Cursor c=db.workers()){while(c.moveToNext())if("WORKER".equals(c.getString(3)))names.add(c.getString(1));}Spinner worker=new Spinner(this);worker.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names));int selected=ids.indexOf((int)oldWorkerId);worker.setSelection(Math.max(0,selected));box.addView(name);box.addView(fuel);box.addView(price);box.addView(reading);box.addView(Util.label(this,"العامل المسؤول في النهار"));box.addView(worker);new AlertDialog.Builder(this).setTitle("تعديل الطرمبة").setView(box).setPositiveButton("حفظ",(d,w)->{if(names.isEmpty())return;db.updatePump(id,name.getText().toString(),fuel.getText().toString(),Util.number(price.getText().toString()),Util.number(reading.getText().toString()),ids.get(worker.getSelectedItemPosition()));pumps();}).setNegativeButton("إلغاء",null).show();}
    private void approvals(){shell("بانتظار اعتماد المدير");try(Cursor c=db.submitted()){if(c.getCount()==0)content.addView(Util.label(this,"لا توجد ورديات بانتظار الاعتماد."));while(c.moveToNext()){long id=c.getLong(0);String worker=c.getString(1),date=c.getString(2),reason=c.getString(5);double sales=c.getDouble(3),balance=c.getDouble(4);Button b=Util.button(this,"وردية #"+id+" — "+worker+"\n"+date+" | المبيعات: "+fmt(sales)+" | الباقي: "+fmt(balance)+(reason.isEmpty()?"":"\nالسبب: "+reason));b.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("اعتماد الوردية #"+id).setMessage("بعد الاعتماد تصبح قراءات الإغلاق بداية الوردية التالية.").setPositiveButton("اعتماد",(d,w)->{db.approve(id);new Sync(this).run(false);approvals();}).setNegativeButton("إلغاء",null).show());content.addView(b);}}back();}
    private LinearLayout form(){LinearLayout b=new LinearLayout(this);b.setPadding(28,8,28,0);b.setOrientation(LinearLayout.VERTICAL);return b;}
    private EditText input(String hint,String value,boolean number){EditText e=new EditText(this);e.setHint(hint);e.setText(value);if(number)e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);return e;}
    private String fmt(double n){return n==Math.rint(n)?String.format(Locale.US,"%.0f",n):String.format(Locale.US,"%.2f",n);}
    @Override public void onBackPressed(){home();}
}
