package com.alameer.station.shifts;

import android.app.*;import android.content.*;import android.net.*;import android.os.*;import android.provider.Settings;import android.widget.*;import org.json.JSONObject;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;

public class AppUpdater {
    private final Activity activity;
    public AppUpdater(Activity a){activity=a;}

    public void check(boolean userRequested){
        String url=BuildConfig.UPDATE_MANIFEST_URL;
        if(url==null||url.trim().isEmpty()){
            if(userRequested)new AlertDialog.Builder(activity).setTitle("التحديث").setMessage("سيُفعّل فحص التحديث عند ربط عنوان التحديث المركزي في النسخة الرسمية.").setPositiveButton("حسنًا",null).show();
            return;
        }
        if(userRequested)Toast.makeText(activity,"جاري فحص التحديث...",Toast.LENGTH_SHORT).show();
        new Thread(()->{try{JSONObject j=new JSONObject(readUrl(url));long latest=j.getLong("versionCode");long current=BuildConfig.VERSION_CODE;if(latest>current){activity.runOnUiThread(()->showUpdate(j));}else if(userRequested){activity.runOnUiThread(()->Toast.makeText(activity,"لديك أحدث نسخة",Toast.LENGTH_SHORT).show());}}catch(Exception e){if(userRequested)activity.runOnUiThread(()->Toast.makeText(activity,"تعذر فحص التحديث. تحقق من الإنترنت.",Toast.LENGTH_LONG).show());}}).start();
    }
    private String readUrl(String address)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(address).openConnection();c.setConnectTimeout(12000);c.setReadTimeout(12000);c.setRequestProperty("Accept","application/json");try(InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))>0)out.write(b,0,n);return out.toString(StandardCharsets.UTF_8.name());}finally{c.disconnect();}}
    private void showUpdate(JSONObject j){String version=j.optString("versionName","جديدة"),notes=j.optString("notes","تحسينات وإصلاحات"),apk=j.optString("apkUrl","");boolean required=j.optBoolean("required",false);AlertDialog d=new AlertDialog.Builder(activity).setTitle("تحديث متوفر — "+version).setMessage(notes).setPositiveButton("تنزيل وتثبيت",(x,w)->download(apk)).setNegativeButton(required?"لاحقًا":"إلغاء",null).create();d.setCanceledOnTouchOutside(!required);d.show();}
    private void download(String apkUrl){if(apkUrl==null||apkUrl.trim().isEmpty()){Toast.makeText(activity,"رابط ملف التحديث غير صالح",Toast.LENGTH_LONG).show();return;}if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O&&!activity.getPackageManager().canRequestPackageInstalls()){new AlertDialog.Builder(activity).setTitle("السماح بالتحديث").setMessage("اسمح لمحطة الأمير بتثبيت التحديث، ثم ارجع واضغط فحص التحديث مرة أخرى.").setPositiveButton("فتح الإعدادات",(d,w)->activity.startActivity(new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES, Uri.parse("package:"+activity.getPackageName())))).setNegativeButton("إلغاء",null).show();return;}DownloadManager.Request r=new DownloadManager.Request(Uri.parse(apkUrl));r.setTitle("تحديث محطة الأمير");r.setDescription("جاري تنزيل النسخة الجديدة");r.setMimeType("application/vnd.android.package-archive");r.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED);r.setDestinationInExternalFilesDir(activity,Environment.DIRECTORY_DOWNLOADS,"AlameerStation-update.apk");DownloadManager dm=(DownloadManager)activity.getSystemService(Context.DOWNLOAD_SERVICE);long id=dm.enqueue(r);BroadcastReceiver receiver=new BroadcastReceiver(){@Override public void onReceive(Context context,Intent intent){if(intent.getLongExtra(DownloadManager.EXTRA_DOWNLOAD_ID,-1)!=id)return;try{Uri uri=dm.getUriForDownloadedFile(id);Intent install=new Intent(Intent.ACTION_VIEW);install.setDataAndType(uri,"application/vnd.android.package-archive");install.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_ACTIVITY_NEW_TASK);context.startActivity(install);}finally{context.unregisterReceiver(this);}}};IntentFilter f=new IntentFilter(DownloadManager.ACTION_DOWNLOAD_COMPLETE);if(Build.VERSION.SDK_INT>=33)activity.registerReceiver(receiver,f,Context.RECEIVER_NOT_EXPORTED);else activity.registerReceiver(receiver,f);Toast.makeText(activity,"بدأ تنزيل التحديث",Toast.LENGTH_LONG).show();}
}
