package com.alameer.station.shifts;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class DashboardActivity extends Activity {
    int workerId;String name,role;Db db;
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new Db(this);workerId=getIntent().getIntExtra("workerId",0);name=getIntent().getStringExtra("name");role=getIntent().getStringExtra("role");build();}
    private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,36,24,24);root.setBackgroundColor(Color.rgb(247,250,252));root.addView(Util.title(this,"محطة الأمير"),new LinearLayout.LayoutParams(-1,-2));root.addView(Util.label(this,"مرحبًا، "+name+"\n"+new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date())));if(!"ADMIN".equals(role)){Button start=Util.button(this,"استلام / متابعة الوردية");start.setOnClickListener(v->{boolean night=db.isNightWorker(workerId);long id=db.openShift(workerId,night);Intent i=new Intent(this,ShiftActivity.class);i.putExtra("shiftId",id);i.putExtra("workerId",workerId);i.putExtra("workerName",name);startActivity(i);});root.addView(start);}else{TextView admin=Util.label(this,"لوحة المدير\nالنسخة الحالية تعرض أرشيف جميع الورديات. إعداد العمال والطرمبات والمزامنة المركزية ضمن الخطوة التالية.");root.addView(admin);}Button archive=Util.button(this,"أرشيف الورديات");archive.setOnClickListener(v->{Intent i=new Intent(this,ArchiveActivity.class);i.putExtra("workerId",workerId);i.putExtra("admin","ADMIN".equals(role));startActivity(i);});root.addView(archive);Button update=Util.button(this,"فحص تحديث التطبيق");update.setOnClickListener(v->new AppUpdater(this).check(true));root.addView(update);Button out=Util.button(this,"تسجيل الخروج");out.setOnClickListener(v->finish());root.addView(out);setContentView(root);new AppUpdater(this).check(false);}
}
