package com.alameer.station.shifts;

import android.app.*;import android.os.*;import android.content.*;import android.widget.*;import java.text.*;import java.util.*;

public class DashboardActivity extends Activity {
    int workerId;String name,role;Db db;LinearLayout root;
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new Db(this);workerId=getIntent().getIntExtra("workerId",0);name=getIntent().getStringExtra("name");role=getIntent().getStringExtra("role");build();}
    @Override protected void onResume(){super.onResume();if(root!=null)build();}
    private void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,30,20,28);root.setBackgroundColor(Util.BG);root.addView(Util.title(this,"محطة الأمير\nإدارة الورديات"),Util.spaced());root.addView(Util.card(this,"مرحبًا، "+name+"\n"+new SimpleDateFormat("EEEE، yyyy-MM-dd",new Locale("ar")).format(new Date())),Util.spaced());if(!"ADMIN".equals(role)){Button start=Util.goldButton(this,"استلام / متابعة الوردية");start.setOnClickListener(v->{long id=db.openShift(workerId,db.isNightWorker(workerId));Intent i=new Intent(this,ShiftActivity.class);i.putExtra("shiftId",id);i.putExtra("workerId",workerId);i.putExtra("workerName",name);startActivity(i);});root.addView(start,Util.spaced());}else{int pending=db.pendingCount();int waitingSync=db.pendingSyncCount();TextView status=Util.card(this,pending==0?"✓ لا توجد ورديات معلقة":"لديك "+pending+" وردية بانتظار الاعتماد");status.setTextColor(pending==0?Util.GREEN:Util.RED);root.addView(status,Util.spaced());Button syncNow=Util.button(this,"مزامنة الآن"+(waitingSync>0?" ("+waitingSync+")":""));syncNow.setOnClickListener(v->{Sync manual=new Sync(this);manual.run(true);manual.pullPrices(true);});root.addView(syncNow,Util.spaced());Button approvals=Util.goldButton(this,"اعتماد الورديات"+(pending>0?" ("+pending+")":""));approvals.setOnClickListener(v->{Intent i=new Intent(this,AdminActivity.class);i.putExtra("screen","approvals");startActivity(i);});root.addView(approvals,Util.spaced());Button settings=Util.button(this,"إعداد العمال والطرمبات");settings.setOnClickListener(v->startActivity(new Intent(this,AdminActivity.class)));root.addView(settings,Util.spaced());}Button archive=Util.button(this,"أرشيف الورديات");archive.setOnClickListener(v->{Intent i=new Intent(this,ArchiveActivity.class);i.putExtra("workerId",workerId);i.putExtra("admin","ADMIN".equals(role));startActivity(i);});root.addView(archive,Util.spaced());Button update=Util.button(this,"فحص تحديث التطبيق");update.setOnClickListener(v->new AppUpdater(this).check(true));root.addView(update,Util.spaced());Button out=Util.dangerButton(this,"تسجيل الخروج");out.setOnClickListener(v->finish());root.addView(out,Util.spaced());ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.addView(root);root.setLayoutDirection(android.view.View.LAYOUT_DIRECTION_RTL);setContentView(scroll);new AppUpdater(this).check(false);Sync auto=new Sync(this);auto.run(false);auto.pullPrices(false);}
}
